language: node_js
node_js:
  - 4.1.0
  - 4.0.0
  - 0.12
  - 0.11
  - 0.10
  - iojs-v3.0.0
  - iojs-v2.0.0
  - iojs-v1.0.0
sudo: false
script:
  - npm run test-ci
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - rm -rf ./coverage
addons:
  code_climate:
    repo_token:
      secure: "GM2ef9DOdGP63gXdOis2PVCGeseR4UJ0dgvE8QrsW0rHUj0I/DsaDWUIq7vBx8EHgaYllVrKXsm1eWvSR5KTdufIICH9B/itTQVBWOXf8sTIphURLab4nmaSs272hs7VH2MU6wTArinQbP4tza6kC/yh66YHnMcho/a/bUHs5SzgHdWBZRnMbUtfkGPdB5V2TAtXBmDX/113CSqqYIgBOJFWA4UTWlNxQzQ4d4mT2tCsYkVdko4Lj0llJfWHhTCgoFlDDEKeH3S8nvXpTf/SQemZ8CX+PsTMyKd8ZWGrOl3BPbv4cutqu7zZc+2uh5R1EFp1PApkWtbk+5X973wmuQYgkTFBfdGnJnb1mMskZ668d7epRgOaZiWxkV6ZKLNtB6g7PvKwUxxfdq1SBLlzNPYxEV5FFZX0PQX85mJNI5mmWq/m0PnF1MuRtIgtoFlMoq7eheI+v2WVHVVxzAl/IY1f+kqX/NxDzdqMdFQGw2SVcGK5XwTimu4A3wi8+laB1SJvUXv2S0O0WMjJPVWBWXQlWpB55f/yhLP/0zoQyitClJKO94AeQAo9yJQWAu5yVuOohcUXXCs3WS3hSirkc8TnJnFOgguUxsNN2f2Kxj1h1Hn+pgIrdpbKzwERGUSPq9zxi5wScPqIey4LHIwF9e05K3trRN8Oc2DcALgnyho="